#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "http://github.com/shirtable/2015-12-12-baltimore"
workshop_site   : "http://shirtable.github.io/2015-12-12-baltimore"
#--------------------------------------------------------------------------------
# Our organization settings - adapted from SWC defaults
#--------------------------------------------------------------------------------
org_github      : "http://github.com/shirtable"
org_twitter     : "http://twitter.com/ShirtableDotIO"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "http://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "http://files.software-carpentry.org"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_lessons     : "http://software-carpentry.org/v5/novice"
swc_site        : "http://software-carpentry.org"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
